language: c
compiler:
- gcc
env:
- LANG=C
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq g++ gccxml reprepro devscripts docbook-to-man libgc-dev libperl-dev
  libgc1c2 coreutils netcat-openbsd curl
install:
- ./install.sh -plain -bootstrap
- work/packaging/build_debian.sh
- sudo dpkg -i work/packaging/debs/*.deb
- rm -rf $HOME/.config/liberty-eiffel
script:
- work/se_run_tutorial.sh
cache:
- apt
notifications:
  slack:
    secure: NLCxaRIda57mSi5Bv8tYJp+sB110tXtmOPRbcdqdAdWjv5csatyqUB3U/QCsNPR0KrUE4Z8Abp+LS75TZXthKUs6It8Emns4RZtdjsJBZBOc1jD89YNRt2ogDZTXJh47XymvruMuBXRKOrAthBRFFI4Zsk45ivgfw0egcN7+Ua8=
